# Generated by Django 5.2.7 on 2025-10-25 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pageview_ip_address_pageview_referrer_and_more'),
        ('blog', '0002_blogpost_excerpt_blogpost_is_published_blogpost_slug_and_more'),
        ('properties', '0008_alter_image_options_image_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialShareAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('email', 'Email'), ('copy-link', 'Copy Link'), ('native-share', 'Native Share'), ('other', 'Other')], max_length=20)),
                ('total_shares', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('property_shares', models.IntegerField(default=0)),
                ('blog_shares', models.IntegerField(default=0)),
                ('other_shares', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'platform'],
                'unique_together': {('date', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='SocialShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('email', 'Email'), ('copy-link', 'Copy Link'), ('native-share', 'Native Share'), ('other', 'Other')], max_length=20)),
                ('content_type', models.CharField(choices=[('property', 'Property Listing'), ('blog_post', 'Blog Post'), ('blog_list', 'Blog List Page'), ('homepage', 'Homepage'), ('other', 'Other Page')], default='other', max_length=20)),
                ('url_shared', models.URLField(help_text='The URL that was shared')),
                ('page_title', models.CharField(help_text='Title of the page that was shared', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.URLField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like share location, device type, etc.')),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='blog.blogpost')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['platform', 'timestamp'], name='analytics_s_platfor_a0175c_idx'), models.Index(fields=['content_type', 'timestamp'], name='analytics_s_content_8d4b9e_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_160f4f_idx')],
            },
        ),
    ]
