# Generated by Django 5.2.7 on 2025-10-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('properties', '0004_property_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
