# Generated by Django 5.2.7 on 2025-10-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinquiry_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('property', 'Property Inquiry'), ('support', 'Technical Support'), ('partnership', 'Partnership'), ('complaint', 'Complaint')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
