# Generated by Django 5.2.7 on 2025-10-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('buyer', 'Buyer')], default='tenant', max_length=10),
        ),
    ]
