# Generated by Django 5.2.7 on 2025-10-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_premium_user_premium_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium_expires',
        ),
    ]
