# Generated by Django 5.2.7 on 2025-10-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_premium_remove_user_premium_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
