# Generated by Django 5.2.7 on 2025-10-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('zoning', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_lease', 'For Lease'), ('sold', 'Sold'), ('leased', 'Leased')], default='for_sale', max_length=20)),
                ('cap_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('noi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rent_roll', models.TextField(blank=True, null=True)),
                ('expense_summaries', models.TextField(blank=True, null=True)),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('broker_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='properties.amenity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
