# Generated by Django 5.2.7 on 2025-10-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
