# Generated by Django 5.2.7 on 2025-10-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_floor_plan_image_property_virtual_tour_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
