# Generated by Django 5.2.7 on 2025-10-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
