# Generated by Django 5.2.7 on 2025-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_company_alter_property_country_property_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
