# Generated by Django 5.2.7 on 2025-10-17 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_listing', to='properties.property')),
            ],
        ),
    ]
