# Generated by Django 5.2.7 on 2025-10-19 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumlisting',
            old_name='activated_at',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='premiumlisting',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic Premium'), ('featured', 'Featured Listing'), ('premium', 'Premium Plus')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
