# Generated by Django 5.2.7 on 2025-10-19 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_rename_activated_at_premiumlisting_start_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumlisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='payment_details',
            field=models.JSONField(blank=True, help_text='Additional payment information', null=True),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('qr_payment', 'QR Code Payment'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash Payment'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='premiumlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
