"""
Django settings for real_estate project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-en6xc^isgg1gl(f*ptl%#hao8ewsj$kbpeh%s!*7+%fo2%q@tx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.0/24', '10.0.0.0/8']

# Admin Security Settings
ADMIN_ENABLED = True
ADMIN_RESTRICTED_ACCESS = True
ALLOWED_ADMIN_IPS = [
    '127.0.0.1',
    'localhost',
    '192.168.1.0/24',  # Local network
    '10.0.0.0/8',      # Private network
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CSRF Protection
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth

    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.instagram',
    'crispy_forms',

    # Local apps
    'accounts',
    'properties',
    'premium',
    'analytics',
    'contact',
    'blog',
    'legal',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'real_estate.middleware.AdminSecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
]

ROOT_URLCONF = 'real_estate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'real_estate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Django Allauth Configuration
SITE_ID = 1

# Account settings (updated to avoid deprecation warnings)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification for development
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = False

# Crispy forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Login/logout settings
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Social account settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0'
    },
    'linkedin_oauth2': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        }
    },
    'twitter': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        }
    },
    'instagram': {
        'APP': {
            'client_id': '',
            'secret': '',
            'key': ''
        }
    }
}


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'  # Replace with actual email
EMAIL_HOST_PASSWORD = 'your-app-password'  # Replace with app password
DEFAULT_FROM_EMAIL = 'admin@gorkharealestate.com'


# Premium Email Templates
PREMIUM_EMAIL_SUBJECTS = {
    'premium_activated': '🎉 Your Property is Now Premium!',
    'premium_expiring': '⏰ Your Premium Listing Expires Soon',
    'premium_expired': '❌ Your Premium Listing Has Expired',
    'payment_received': '💰 Payment Received - Thank You!',
    'payment_failed': '⚠️ Payment Failed - Please Try Again',
}

PREMIUM_EMAIL_TEMPLATES = {
    'premium_activated': '''
Dear {user_name},

Congratulations! Your property "{property_title}" has been successfully upgraded to premium status.

Premium Plan: {plan_type}
Duration: {duration_days} days
End Date: {end_date}

Benefits of your premium upgrade:
✓ Higher visibility in search results
✓ Featured badge display
✓ Detailed analytics dashboard
✓ Priority customer support

You can monitor your premium performance at: {dashboard_url}

Thank you for choosing Gorkha Real Estate!

Best regards,
Gorkha Real Estate Team
admin@gorkharealestate.com
    ''',

    'premium_expiring': '''
Dear {user_name},

This is a reminder that your premium listing for "{property_title}" will expire in {days_remaining} days.

Current Plan: {plan_type}
Expiry Date: {end_date}

To continue enjoying premium benefits:
✓ Renew your listing before expiry
✓ Maintain high visibility for your property
✓ Keep receiving detailed analytics

Renew now: {renewal_url}

Don't miss out on potential buyers!

Best regards,
Gorkha Real Estate Team
admin@gorkharealestate.com
    ''',

    'premium_expired': '''
Dear {user_name},

Your premium listing for "{property_title}" has expired.

Expired Plan: {plan_type}
Expired on: {end_date}

To restore premium benefits:
✓ Upgrade again at competitive rates
✓ Regain high search visibility
✓ Access detailed performance analytics

Upgrade now: {plans_url}

We hope to serve you again!

Best regards,
Gorkha Real Estate Team
admin@gorkharealestate.com
    ''',

    'payment_received': '''
Dear {user_name},

Thank you for your payment! We've received your payment for the premium upgrade.

Property: {property_title}
Plan: {plan_type}
Amount Paid: NPR {amount_paid}
Payment ID: {payment_id}

Your premium listing is now active and will be valid until {end_date}.

Track your listing performance: {dashboard_url}

Best regards,
Gorkha Real Estate Team
admin@gorkharealestate.com
    ''',

    'payment_failed': '''
Dear {user_name},

We were unable to process your payment for the premium upgrade.

Property: {property_title}
Plan: {plan_type}
Amount: NPR {amount}

Payment ID: {payment_id}

Possible reasons for payment failure:
• Insufficient funds
• Card declined
• Network issues
• Payment method error

Please try again with a different payment method or contact our support.

Try again: {checkout_url}
Contact us: support@gorkharealestate.com

Best regards,
Gorkha Real Estate Team
admin@gorkharealestate.com
    ''',
}
